### ISSUE TITLE
Minor typo in first notebook

### ISSUE THREAD

**Issue by javirudolph** [PracticumAI/python#59]
Hi there, found another typo but wasn't sure if doing a pull request was easier or just an issue. So trying the second one here, where the word **single** is typed **singe**

https://github.com/PracticumAI/python/blame/a9c2f58d1eea4c62bab69586417a0a553f655b84/01.1_getting_started.ipynb#L883

**Comment by magitz** [comment]
Thanks for the report. This has been fixed.
